# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1454bd753e209ec8fc5df98fd23967ced2e75e7de7b0c5c720320a1e1b5db87be92a5c865684a04055bfed39e339315b7f856cdacf0a97ebc2197068bc9bd5f7

test:
  secret_key_base: 49b80f05c6791a43d731b42f861d9aa615358e458b60e6bfb04fd97b40ea23e547e390c9eb4d3d7c98557146b5d6608a22d0db17eaeef75e77c1d1705d4a7f44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
